export interface RuntimeEnv {
  VITE_FIREBASE_API_KEY?: string;
  VITE_FIREBASE_AUTH_DOMAIN?: string;
  VITE_FIREBASE_PROJECT_ID?: string;
  VITE_FIREBASE_STORAGE_BUCKET?: string;
  VITE_FIREBASE_MESSAGING_SENDER_ID?: string;
  VITE_FIREBASE_APP_ID?: string;
  VITE_FIREBASE_MEASUREMENT_ID?: string;
  VITE_DEFAULT_USER_ROLE?: 'admin' | 'user';
  VITE_AI_ENDPOINT_URL?: string;
  VITE_AI_ENDPOINT_TOKEN?: string;
}

export function getRuntimeEnv(): RuntimeEnv {
  const raw = import.meta.env as Record<string, string | undefined>;
  const defaults: RuntimeEnv = {
    VITE_DEFAULT_USER_ROLE: 'admin'
  };

  return {
    VITE_FIREBASE_API_KEY: raw.VITE_FIREBASE_API_KEY,
    VITE_FIREBASE_AUTH_DOMAIN: raw.VITE_FIREBASE_AUTH_DOMAIN,
    VITE_FIREBASE_PROJECT_ID: raw.VITE_FIREBASE_PROJECT_ID,
    VITE_FIREBASE_STORAGE_BUCKET: raw.VITE_FIREBASE_STORAGE_BUCKET,
    VITE_FIREBASE_MESSAGING_SENDER_ID: raw.VITE_FIREBASE_MESSAGING_SENDER_ID,
    VITE_FIREBASE_APP_ID: raw.VITE_FIREBASE_APP_ID,
    VITE_FIREBASE_MEASUREMENT_ID: raw.VITE_FIREBASE_MEASUREMENT_ID,
    VITE_DEFAULT_USER_ROLE: (raw.VITE_DEFAULT_USER_ROLE as RuntimeEnv['VITE_DEFAULT_USER_ROLE']) || defaults.VITE_DEFAULT_USER_ROLE,
    VITE_AI_ENDPOINT_URL: raw.VITE_AI_ENDPOINT_URL,
    VITE_AI_ENDPOINT_TOKEN: raw.VITE_AI_ENDPOINT_TOKEN
  };
}

export function hasFirebaseConfig(env: RuntimeEnv): boolean {
  return Boolean(
    env.VITE_FIREBASE_API_KEY &&
      env.VITE_FIREBASE_AUTH_DOMAIN &&
      env.VITE_FIREBASE_PROJECT_ID &&
      env.VITE_FIREBASE_STORAGE_BUCKET &&
      env.VITE_FIREBASE_MESSAGING_SENDER_ID &&
      env.VITE_FIREBASE_APP_ID
  );
}
